version: "3.0"
services:
  code-server:
    image: r-code-server:${VERSION}
    container_name: ${CONTAINER_NAME}
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        R_VERSION: ${R_VERSION}
    restart: unless-stopped
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - PROXY_DOMAIN=${PROXY_DOMAIN}
      - INSTALL_EXTENSIONS=1
    ports:
      - ${CODE_SERVER_PORT}:8443
    command: code-server
