version: "3.0"
services:
  code-server:
    image: ${IMAGE_NAME}:${VERSION}
    container_name: ${CONTAINER_NAME}
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        R_VERSION: ${R_VERSION}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - INSTALL_EXTENSIONS=true
    ports:
      - ${CODE_SERVER_PORT}:8443
    volumes:
      - ${WORKSPACE_PATH}:/config/workspace
      - ${APPDATA_PATH}:/config
      - ./env_config/install_extensions.sh:/config/custom-cont-init.d/install_extensions.sh